import 'package:cloud_firestore/cloud_firestore.dart';

import 'package:testproject/models/task_recurrence.dart';

/// A single day's occurrence of an existing task, shown on the
/// ActivityProgress calendar (see phase1_calendar_ui_prompt.md and
/// phase2_recurring_tasks_prompt.md). This is a thin read view over a
/// `tasks` document — it does NOT redesign the task data model.
class CalendarEvent {
  final String taskId;
  final String title;
  final String category;
  final String dosage;
  final String status;
  final DateTime dueDate;

  /// True for any occurrence generated by recurrence expansion, including
  /// the literal stored one. There is no per-occurrence completion
  /// tracking yet (out of scope for Phase 2 — see the recurring-tasks
  /// report), so recurring occurrences show a "Repeats" indicator instead
  /// of the completed/missed/pending [status] badge non-recurring tasks
  /// use — [status] would otherwise misleadingly apply one document's
  /// status to every computed future date.
  final bool isRecurring;
  final RecurrenceType recurrenceType;
  final RecurrenceRule recurrenceRule;

  const CalendarEvent({
    required this.taskId,
    required this.title,
    required this.category,
    required this.dosage,
    required this.status,
    required this.dueDate,
    required this.isRecurring,
    required this.recurrenceType,
    required this.recurrenceRule,
  });

  /// Expands one task doc into its occurrences within [rangeStart]..
  /// [rangeEnd] (inclusive, date-only) using [getOccurrencesForDateRange]
  /// — the single source of truth for recurrence expansion (Step 10).
  /// Returns an empty list for a task with no/invalid due date, so the
  /// calendar can skip it rather than crash.
  static List<CalendarEvent> occurrencesFromDoc(
    QueryDocumentSnapshot doc,
    DateTime rangeStart,
    DateTime rangeEnd,
  ) {
    final data = doc.data() as Map<String, dynamic>;
    final dueTs = data['dueDate'];
    if (dueTs is! Timestamp) return const [];

    final series = TaskSeries.fromDoc(doc);
    final occurrences =
        getOccurrencesForDateRange(series, rangeStart, rangeEnd);

    final String title = (data['title'] ?? '') as String;
    final String category = (data['category'] ?? '') as String;
    final String dosage = (data['dosage'] ?? '') as String;
    final String status = (data['status'] ?? 'pending') as String;
    final bool isRecurring = series.recurrenceType != RecurrenceType.none;

    return occurrences
        .map((occurrenceDate) => CalendarEvent(
              taskId: doc.id,
              title: title,
              category: category,
              dosage: dosage,
              status: status,
              dueDate: occurrenceDate,
              isRecurring: isRecurring,
              recurrenceType: series.recurrenceType,
              recurrenceRule: series.rule,
            ))
        .toList();
  }
}
