// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpfwrwFLJsHCL7Mm3LW1KUQrdG94yboqw',
    appId: '1:272241804705:web:e12be8e5416b8a7212b7e0',
    messagingSenderId: '272241804705',
    projectId: 'cognitiveanddailyassistanceapp',
    authDomain: 'cognitiveanddailyassistanceapp.firebaseapp.com',
    databaseURL: 'https://cognitiveanddailyassistanceapp-default-rtdb.firebaseio.com',
    storageBucket: 'cognitiveanddailyassistanceapp.firebasestorage.app',
    measurementId: 'G-0RHXSZ1W0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS7X68YQKMLyS8T5R4ry-g56kKEYiRFzI',
    appId: '1:272241804705:android:0d32ba8421614a3112b7e0',
    messagingSenderId: '272241804705',
    projectId: 'cognitiveanddailyassistanceapp',
    databaseURL: 'https://cognitiveanddailyassistanceapp-default-rtdb.firebaseio.com',
    storageBucket: 'cognitiveanddailyassistanceapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi66WJsUfVHg8ck4cxKY8l1HP29IYh8DU',
    appId: '1:272241804705:ios:14d785a577b32d4912b7e0',
    messagingSenderId: '272241804705',
    projectId: 'cognitiveanddailyassistanceapp',
    databaseURL: 'https://cognitiveanddailyassistanceapp-default-rtdb.firebaseio.com',
    storageBucket: 'cognitiveanddailyassistanceapp.firebasestorage.app',
    iosClientId: '272241804705-vu1tovok7ikr2d6q3dm6aiakttlkvr0u.apps.googleusercontent.com',
    iosBundleId: 'com.example.testproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi66WJsUfVHg8ck4cxKY8l1HP29IYh8DU',
    appId: '1:272241804705:ios:14d785a577b32d4912b7e0',
    messagingSenderId: '272241804705',
    projectId: 'cognitiveanddailyassistanceapp',
    databaseURL: 'https://cognitiveanddailyassistanceapp-default-rtdb.firebaseio.com',
    storageBucket: 'cognitiveanddailyassistanceapp.firebasestorage.app',
    iosClientId: '272241804705-vu1tovok7ikr2d6q3dm6aiakttlkvr0u.apps.googleusercontent.com',
    iosBundleId: 'com.example.testproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpfwrwFLJsHCL7Mm3LW1KUQrdG94yboqw',
    appId: '1:272241804705:web:0ce4bbb7711bc67e12b7e0',
    messagingSenderId: '272241804705',
    projectId: 'cognitiveanddailyassistanceapp',
    authDomain: 'cognitiveanddailyassistanceapp.firebaseapp.com',
    databaseURL: 'https://cognitiveanddailyassistanceapp-default-rtdb.firebaseio.com',
    storageBucket: 'cognitiveanddailyassistanceapp.firebasestorage.app',
    measurementId: 'G-072B92CNLW',
  );
}
